export enum ActionType {
  // Auth
  AUTH_LOGIN_SUCCESS = 'AUTH_LOGIN_SUCCESS',
  AUTH_LOGOUT = 'AUTH_LOGOUT',
  AUTH_PASSWORD_RESET_REQUESTED = 'AUTH_PASSWORD_RESET_REQUESTED',
  AUTH_PASSWORD_RESET_COMPLETED = 'AUTH_PASSWORD_RESET_COMPLETED',

  // Admin
  ADMIN_CREATED = 'ADMIN_CREATED',
  ADMIN_UPDATED = 'ADMIN_UPDATED',
  ADMIN_ACTIVATED = 'ADMIN_ACTIVATED',
  ADMIN_DEACTIVATED = 'ADMIN_DEACTIVATED',
  ADMIN_DELETED = 'ADMIN_DELETED',

  // Contractor
  CONTRACTOR_CREATED = 'CONTRACTOR_CREATED',
  CONTRACTOR_UPDATED = 'CONTRACTOR_UPDATED',
  CONTRACTOR_ACTIVATED = 'CONTRACTOR_ACTIVATED',
  CONTRACTOR_DEACTIVATED = 'CONTRACTOR_DEACTIVATED',
  CONTRACTOR_DELETED = 'CONTRACTOR_DELETED',
  CONTRACTOR_DEPARTMENT_UPDATED = 'CONTRACTOR_DEPARTMENT_UPDATED',

  // Department
  DEPARTMENT_CREATED = 'DEPARTMENT_CREATED',
  DEPARTMENT_UPDATED = 'DEPARTMENT_UPDATED',
  DEPARTMENT_DELETED = 'DEPARTMENT_DELETED',

  // Category
  CATEGORY_CREATED = 'CATEGORY_CREATED',
  CATEGORY_UPDATED = 'CATEGORY_UPDATED',
  CATEGORY_DELETED = 'CATEGORY_DELETED',

  // Document
  DOCUMENT_CREATED = 'DOCUMENT_CREATED',
  DOCUMENT_UPDATED = 'DOCUMENT_UPDATED',
  DOCUMENT_REUPLOADED = 'DOCUMENT_REUPLOADED',
  DOCUMENT_STATUS_CHANGED = 'DOCUMENT_STATUS_CHANGED',
  DOCUMENT_DEPARTMENT_UPDATED = 'DOCUMENT_DEPARTMENT_UPDATED',
  DOCUMENT_DELETED = 'DOCUMENT_DELETED',
  DOCUMENT_VIEWED = 'DOCUMENT_VIEWED',

  // Video
  VIDEO_CREATED = 'VIDEO_CREATED',
  VIDEO_UPDATED = 'VIDEO_UPDATED',
  VIDEO_STATUS_CHANGED = 'VIDEO_STATUS_CHANGED',
  VIDEO_DEPARTMENT_UPDATED = 'VIDEO_DEPARTMENT_UPDATED',
  VIDEO_DELETED = 'VIDEO_DELETED',
  VIDEO_STREAMED = 'VIDEO_STREAMED',
}
